-- Feuerwehr-Stammdaten (Wehren, Bereich, KBI-Bereich)
CREATE TABLE IF NOT EXISTS feuerwehren (
    id          INT          NOT NULL AUTO_INCREMENT,
    name        VARCHAR(120) NOT NULL,
    bereich     VARCHAR(60)  NOT NULL,
    kbi_bereich VARCHAR(40)  NOT NULL,
    PRIMARY KEY (id),
    INDEX idx_bereich     (bereich),
    INDEX idx_kbi_bereich (kbi_bereich)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO feuerwehren (name, bereich, kbi_bereich) VALUES
('FF Ahornberg', 'TIR Land 2/1', 'TIR Land 2'),
('FF Altglashütte', 'TIR Land 4/3', 'TIR Land 4'),
('FF Atzmannsberg - Köglitz', 'TIR Land 2/3', 'TIR Land 2'),
('FF Bad Neualbenreuth', 'TIR Land 4/1', 'TIR Land 4'),
('FF Bärnau', 'TIR Land 4/3', 'TIR Land 4'),
('FF Beidl', 'TIR Land 4/3', 'TIR Land 4'),
('FF Brand', 'TIR Land 2/2', 'TIR Land 2'),
('FF Dippersreuth', 'TIR Land 4/2', 'TIR Land 4'),
('FF Ebnath', 'TIR Land 2/2', 'TIR Land 2'),
('FF Ellenfeld', 'TIR Land 4/3', 'TIR Land 4'),
('FF Erbendorf', 'TIR Land 3/4', 'TIR Land 3'),
('FF Falkenberg', 'TIR Land 3/1', 'TIR Land 3'),
('FF Fortschau - Kuchenreuth', 'TIR Land 2/1', 'TIR Land 2'),
('FF Friedenfels', 'TIR Land 3/1', 'TIR Land 3'),
('FF Fuchsmühl', 'TIR Land 3/1', 'TIR Land 3'),
('FF Fuhrmannsreuth', 'TIR Land 2/2', 'TIR Land 2'),
('FF Griesbach', 'TIR Land 4/2', 'TIR Land 4'),
('FF Groschlattengrün', 'TIR Land 3/1', 'TIR Land 3'),
('FF Großensees', 'TIR Land 3/3', 'TIR Land 3'),
('FF Großensterz', 'TIR Land 3/3', 'TIR Land 3'),
('FF Großkonreuth', 'TIR Land 4/2', 'TIR Land 4'),
('FF Grötschenreuth', 'TIR Land 3/4', 'TIR Land 3'),
('FF Gumpen', 'TIR Land 3/1', 'TIR Land 3'),
('FF Guttenberg', 'TIR Land 2/3', 'TIR Land 2'),
('FF Hardeck', 'TIR Land 4/1', 'TIR Land 4'),
('FF Helmbrechts', 'TIR Land 3/2', 'TIR Land 3'),
('FF Hermannsreuth', 'TIR Land 4/3', 'TIR Land 4'),
('FF Höflas bei Kemnath', 'TIR Land 2/1', 'TIR Land 2'),
('FF Höflas bei Konnersreuth', 'TIR Land 3/3', 'TIR Land 3'),
('FF Hohenhard', 'TIR Land 3/2', 'TIR Land 3'),
('FF Hohenthan', 'TIR Land 4/3', 'TIR Land 4'),
('FF Immenreuth', 'TIR Land 2/1', 'TIR Land 2'),
('FF Kastl b. Kemnath', 'TIR Land 2/3', 'TIR Land 2'),
('FF Kemnath', 'TIR Land 2/1', 'TIR Land 2'),
('FF Kondrau', 'TIR Land 4/1', 'TIR Land 4'),
('FF Königshütte', 'TIR Land 3/3', 'TIR Land 3'),
('FF Konnersreuth', 'TIR Land 3/3', 'TIR Land 3'),
('FF Kötzersdorf', 'TIR Land 2/1', 'TIR Land 2'),
('FF Krummennaab', 'TIR Land 3/4', 'TIR Land 3'),
('FF Kulmain', 'TIR Land 2/1', 'TIR Land 2'),
('FF Lenau', 'TIR Land 2/1', 'TIR Land 2'),
('FF Lengenfeld bei Tirschenreuth', 'TIR Land 4/2', 'TIR Land 4'),
('FF Lengenfeld bei Waldershof', 'TIR Land 3/2', 'TIR Land 3'),
('FF Leonberg', 'TIR Land 3/3', 'TIR Land 3'),
('FF Liebenstein', 'TIR Land 4/3', 'TIR Land 4'),
('FF Lochau', 'TIR Land 2/2', 'TIR Land 2'),
('FF Löschwitz - Kaibitz', 'TIR Land 2/3', 'TIR Land 2'),
('FF Mähring', 'TIR Land 4/2', 'TIR Land 4'),
('FF Matzersreuth', 'TIR Land 4/2', 'TIR Land 4'),
('FF Mitterteich', 'TIR Land 3/3', 'TIR Land 3'),
('FF Münchenreuth', 'TIR Land 4/1', 'TIR Land 4'),
('FF Naab', 'TIR Land 4/3', 'TIR Land 4'),
('FF Neudorf - Rosenbühl', 'TIR Land 3/3', 'TIR Land 3'),
('FF Neusorg', 'TIR Land 2/2', 'TIR Land 2'),
('FF Oberwappenöst', 'TIR Land 2/1', 'TIR Land 2'),
('FF Ottengrün', 'TIR Land 4/1', 'TIR Land 4'),
('FF Pechbrunn', 'TIR Land 3/1', 'TIR Land 3'),
('FF Pechofen', 'TIR Land 3/3', 'TIR Land 3'),
('FF Pfaffenreuth', 'TIR Land 4/1', 'TIR Land 4'),
('FF Pilgramsreuth', 'TIR Land 2/2', 'TIR Land 2'),
('FF Pilmersreuth an der Straße', 'TIR Land 4/2', 'TIR Land 4'),
('FF Pleußen', 'TIR Land 3/3', 'TIR Land 3'),
('FF Plößberg', 'TIR Land 4/3', 'TIR Land 4'),
('FF Poppenreuth bei Tirschenreuth', 'TIR Land 4/2', 'TIR Land 4'),
('FF Poppenreuth bei Waldershof', 'TIR Land 3/2', 'TIR Land 3'),
('FF Premenreuth', 'TIR Land 3/4', 'TIR Land 3'),
('FF Pullenreuth', 'TIR Land 2/2', 'TIR Land 2'),
('FF Punreuth', 'TIR Land 2/1', 'TIR Land 2'),
('FF Querenbach', 'TIR Land 4/1', 'TIR Land 4'),
('FF Redenbach', 'TIR Land 4/2', 'TIR Land 4'),
('FF Reuth bei Erbendorf', 'TIR Land 3/4', 'TIR Land 3'),
('FF Reuth bei Kastl', 'TIR Land 2/3', 'TIR Land 2'),
('FF Riglasreuth', 'TIR Land 2/2', 'TIR Land 2'),
('FF Rodenzenreuth', 'TIR Land 3/2', 'TIR Land 3'),
('FF Rosall', 'TIR Land 4/2', 'TIR Land 4'),
('FF Röthenbach am Steinwald', 'TIR Land 3/4', 'TIR Land 3'),
('FF Schönficht', 'TIR Land 4/3', 'TIR Land 4'),
('FF Schönhaid - Leugas', 'TIR Land 3/1', 'TIR Land 3'),
('FF Schönkirch', 'TIR Land 4/3', 'TIR Land 4'),
('FF Schönreuth', 'TIR Land 2/3', 'TIR Land 2'),
('FF Schurbach', 'TIR Land 3/2', 'TIR Land 3'),
('FF Schwarzenbach bei Bärnau', 'TIR Land 4/3', 'TIR Land 4'),
('FF Schwarzenreuth', 'TIR Land 2/2', 'TIR Land 2'),
('FF Siegritz', 'TIR Land 3/4', 'TIR Land 3'),
('FF Thanhausen', 'TIR Land 4/3', 'TIR Land 4'),
('FF Thumsenreuth', 'TIR Land 3/4', 'TIR Land 3'),
('FF Tirschenreuth', 'TIR Land 4/2', 'TIR Land 4'),
('FF Trevesen', 'TIR Land 2/2', 'TIR Land 2'),
('FF Unterbruck', 'TIR Land 2/3', 'TIR Land 2'),
('FF Voitenthan', 'TIR Land 3/1', 'TIR Land 3'),
('FF Walbenreuth', 'TIR Land 3/2', 'TIR Land 3'),
('FF Waldeck', 'TIR Land 2/3', 'TIR Land 2'),
('FF Waldershof', 'TIR Land 3/2', 'TIR Land 3'),
('FF Waldsassen', 'TIR Land 4/1', 'TIR Land 4'),
('FF Wernersreuth', 'TIR Land 4/1', 'TIR Land 4'),
('FF Wetzldorf', 'TIR Land 3/4', 'TIR Land 3'),
('FF Wiesau', 'TIR Land 3/1', 'TIR Land 3'),
('FF Wildenau', 'TIR Land 4/3', 'TIR Land 4'),
('FF Wildenreuth', 'TIR Land 3/4', 'TIR Land 3'),
('FF Wondreb', 'TIR Land 4/2', 'TIR Land 4'),
('FF Zinst', 'TIR Land 2/1', 'TIR Land 2'),
('FF Zwergau', 'TIR Land 2/3', 'TIR Land 2'),
('WF Schott AG', 'TIR Land 3/3', 'TIR Land 3'),
('WF Siemens Kemnath', 'TIR Land 2/1', 'TIR Land 2');

-- Fremdschlüssel in groups
ALTER TABLE `groups`
    ADD COLUMN feuerwehr_id INT NULL AFTER kbm_area,
    ADD CONSTRAINT fk_groups_feuerwehr
        FOREIGN KEY (feuerwehr_id) REFERENCES feuerwehren (id) ON DELETE SET NULL;
